#!/usr/bin/env bash
# 
# File:
#   configurations
# 
# Description:
#   Configurations for scripts in this directory
# 
# Note:
#   Variable "HERE" is defined in the sourcing scripts (locatefile and updatedb)
#   and is assigned the path to the current directory.
# 

# Directory of file paths files database
FILE_PATHS_DATABASE_DIRECTORY="${HERE}/file_paths_database"

# Directory of directory paths files database
DIRECTORY_PATHS_DATABASE_DIRECTORY="${HERE}/directory_paths_database"

# Names of files used in both databases
#   These file names must match the file names in filepaths. Note: The files
#   will be searched in in the given order.
DATABASE_FILE_NAMES=('mount-drive-1-paths' 'mount-drive-2-paths' 'home-paths')

# Paths of mounted drives containing files to be located
#   When a databse file or directory path begins with "{MNTPNT_PATH}/", these
#   paths will traversed through in place of the "{MNTPNT_PATH}" placeholder
#   until the file or directory is found. Database paths beginning with
#   "{MNTPNT_PATH}/" are created when a database file/directory output path
#   defined in updatedb is prefixed with one of these paths.
MOUNTPOINT_PATHS=(
  '/mnt/usb1'
  '/mnt/usb2'
  '/mnt/usb3'
  '/mnt/usb4'
)

# Remove all databases files before updating databases
REMOVE_DATABASE_FILES_BEFORE_UPDATING_DATABASES=true

