#!/usr/bin/env bash
# 
# File:
#   configurations
# 
# Description:
#   The configurations for Locatefile
# 
# Note:
#   Variable "HERE" is defined in the sourcing scripts (locatefile and updatedb)
#   and is assigned the path to the current directory.
# 

# Directory of file paths files database
FILE_PATHS_DATABASE_DIRECTORY="${HERE}/database/file_paths"

# Directory of directory paths files database
DIRECTORY_PATHS_DATABASE_DIRECTORY="${HERE}/database/directory_paths"

# Names of files used in both databases
#   These file names must match the file names in dbfilepaths. Note: These files
#   will be searched in in the given order.
DATABASE_FILE_NAMES=('home-paths' 'mount-drive-1-paths' 'mount-drive-2-paths')

# Paths of mounted drives containing files to be located
#   When a databse file or directory path begins with "{MNTPNT_PATH}/", these
#   paths will traversed through in place of the "{MNTPNT_PATH}" placeholder
#   until the file or directory is found. Database paths beginning with
#   "{MNTPNT_PATH}/" are created when a database file/directory output path
#   defined in updatedb is prefixed with one of these paths.
MOUNTPOINT_PATHS=(
  '/mnt/usb1'
  '/mnt/usb2'
  '/mnt/usb3'
  '/mnt/usb4'
)

# Remove all files from the databases before updating them
REMOVE_DATABASE_FILES_BEFORE_UPDATING_DATABASES=true

