#!/usr/bin/env bash
# 
# File:
#   CONFIGURATIONS
# 
# Description:
#   The configurations for Locatefile
# 
# Note:
#   Variable "HERE" is defined in scripts locatefile and updatedb and this
#   file is sourced within them. HERE is assigned the absolute path of directory
#   "locatefile".
# 

# ======= PRIMARY CONFIGURATIONS (CHANGES REQUIRED) ==============

# Names of files used in both database file and directory paths directories
# NOTES:
#   These names must match the names in FILEPATHS.
#   They are searched in the given order.
DATABASE_FILE_NAMES=('home-paths' 'project-paths')

# ======= ! PRIMARY CONFIGURATIONS (CHANGES REQUIRED) ==============

# ======= SECONDARY CONFIGURATIONS (CHANGES NOT REQUIRED) ==============

# Database file and directory paths directories 
DATABASE_FILE_PATHS_DIRECTORY="${HERE}/database/file_paths"
DATABASE_DIRECTORY_PATHS_DIRECTORY="${HERE}/database/directory_paths"

# Paths of mounted drives containing files to be located
#   When a databse file or directory path begins with "{MNTPNT_PATH}/", these
#   paths will traversed through in place of the "{MNTPNT_PATH}" placeholder
#   until the file or directory is found. Database paths beginning with
#   "{MNTPNT_PATH}/" are created when a database file path specified in
#   FILEPATHS is prefixed with one of these paths.
MOUNTPOINT_PATHS=(
  '/mnt/usb1'
  '/mnt/usb2'
  '/mnt/usb3'
  '/mnt/usb4'
)

# Clear the database before updating.
CLEAR_DATABASE_BEFORE_UPDATING=true

# ======= ! SECONDARY CONFIGURATIONS (CHANGES NOT REQUIRED) ==============

