#!/usr/bin/env bash
# 
# File:
#   FILEPATHS
# 
# Description:
#   The file paths to output to the database
# 
# Usage note:
#   A file or directory path for a database is specified using the "find_out"
#   function. It has the following parameters:
#     1. Type of file to output: "f" for files and "d" for directories
#     2. Maximum depth to search (e.g. "0" for no depth [and to output just the
#        file itself] and "1" for the first level subdirectory)
#     3. Path of file where output will be sent
#     4. Path of file or directory to search through (note: accepts wildcards)
#     5. (Optional) Whether or not to disclude dot files; pass "--nodot" to
#        specify true
# 
# Notes:
#   The file names in the case blocks must match those defined in the
#   configurations file.
# 

source "${HERE}/CONFIGURATIONS"

# FILE PATHS

for dbFileName in "${DATABASE_FILE_NAMES[@]}"; do
  dest="${DATABASE_FILE_PATHS_DIRECTORY}/${dbFileName}"

  case "${dbFileName}" in
    'home-paths')
      echo -n '' > "${dest}"

      # Add a single file.
      find_out f 0 "${dest}" '/home/user/documents/my-document.txt'
      # Add all files in a directory.
      find_out f 1 "${dest}" '/home/user/archives/backup'
      # Add all files in a directory and its subdirectories.
      find_out f 2 "${dest}" '/home/user/bin'
      ;;

    'mount-drive-1-paths')
      if mountpoint '/mnt/usb2' >/dev/null; then
        echo -n '' > "${dest}"

        find_out f 0 "${dest}" '/mnt/usb2/general/notes/my-notes.txt'
        find_out f 4 "${dest}" '/mnt/usb2/current' --nodot
      fi
      ;;

    'mount-drive-2-paths')
      if mountpoint '/mnt/usb3' >/dev/null; then
        echo -n '' > "${dest}"

        find_out f 5 "${dest}" '/mnt/usb3/components/main'
        find_out f 2 "${dest}" '/mnt/usb3/global'
      fi
      ;;
  esac
done

# DIRECTORY PATHS

for dbFileName in "${DATABASE_FILE_NAMES[@]}"; do
  dest="${DATABASE_DIRECTORY_PATHS_DIRECTORY}/${dbFileName}"

  case "${dbFileName}" in
    'home-paths')
      echo -n '' > "${dest}"

      # Add a single directory.
      find_out d 0 "${dest}" '/home/user/documents'
      # Add all directories in a directory.
      find_out d 1 "${dest}" '/home/user/archives'
      # Add all directories in a directory and all second level directories.
      find_out d 2 "${dest}" '/home/user/bin'
      ;;
      
    'mount-drive-1-paths')
      if mountpoint '/mnt/usb2' >/dev/null; then
        echo -n '' > "${dest}"

        find_out d 1 "${dest}" '/mnt/usb2/general'
        find_out d 1 "${dest}" '/mnt/usb2/current'
      fi
      ;;

    'mount-drive-2-paths')
      if mountpoint '/mnt/usb3' >/dev/null; then
        echo -n '' > "${dest}"

        find_out d 5 "${dest}" '/mnt/usb3/components/main'
        find_out d 1 "${dest}" '/mnt/usb3/global'
      fi
      ;;
  esac
done

