#!/usr/bin/env bash
# 
# File:
#   locatefile
# 
# Description:
#   Locate a file from a database.
# 

readonly HERE="$(dirname "${0}")"
source "${HERE}/CONFIGURATIONS"

printHelpMessage() {
  echo -ne "\
locatefile

Usage:
  locatefile [options] <file or directory>

Options:
  -o <return occurrence>    return the specified occurrence
  -d           return a directory instead of a file
  -h           show help message
"
}

while getopts :o:dh OPT; do
  case "${OPT}" in
    o) if [[ ! "${OPTARG}" =~ ^[0-9]+$ ]]; then
         echo "locatefile: invalid value \"${OPTARG}\" for option -o" 1>&2
         exit 1
       else
         if [ -z "${OPTARG}" ]; then
           echo 'locatefile: missing argument for option -o' 1>&2
           exit 1
         fi
         OPT_OCCURRENCE_NUMBER="${OPTARG}"
       fi
       ;;
    d) OPT_RETURN_DIRECTORIES='true'
       ;;
    h) printHelpMessage
       exit
       ;;
    \?)
       echo "locatefile: option \"${OPTARG}\" is unknown" 1>&2
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
  echo 'locatefile: no file or directory name specified' 1>&2
  exit 1
fi

# ========================================================
#   Get the mounted mountpoint paths defined by MOUNTPOINT_PATHS
# ========================================================

for mntpntPath in "${MOUNTPOINT_PATHS[@]}"; do
  if [ -d "${mntpntPath}" ] && mountpoint "${mntpntPath}" >/dev/null; then
    mntpntPathsTmp+=("${mntpntPath}")
  fi
done

MOUNTPOINT_PATHS=("${mntpntPathsTmp[@]}")

# ========================================================
#   Search the database
# ========================================================

if [ "${OPT_RETURN_DIRECTORIES}" = 'true' ]; then
  CURRENT_DATABASE_DIRECTORY="${DIRECTORY_PATHS_DATABASE_DIRECTORY}"
else
  CURRENT_DATABASE_DIRECTORY="${FILE_PATHS_DATABASE_DIRECTORY}"
fi

for dbFileName in "${DATABASE_FILE_NAMES[@]}"
do
  if [ ! -f "${CURRENT_DATABASE_DIRECTORY}/${dbFileName}" ]; then
    continue
  fi

  for mtch in $(grep -P "(?<=/)([^/]*)(?=[^/]*${1}[^/]*$)" \
      "${CURRENT_DATABASE_DIRECTORY}/${dbFileName}"); do

    if [[ "${mtch}" = '{MNTPNT_PATH}/'* ]]; then
      for mntpntPath in "${MOUNTPOINT_PATHS[@]}"; do
        mntpntPathMtchPrsd="${mtch//'{MNTPNT_PATH}'/"${mntpntPath}"}"

        if [[ ("${OPT_RETURN_DIRECTORIES}" = 'true' && -d \
            "${mntpntPathMtchPrsd}") || -f "${mntpntPathMtchPrsd}" ]]
        then
          MATCHES+=("${mntpntPathMtchPrsd}")
          ((CURRENT_OCCURRENCE_NUMBER++))
          
          if [ -n "${OPT_OCCURRENCE_NUMBER}" ] && [ "${OPT_OCCURRENCE_NUMBER}" \
              -eq "${CURRENT_OCCURRENCE_NUMBER}" ]; then
            break 3
          fi
        fi
      done
    else
      MATCHES+=("${mtch}")
      ((CURRENT_OCCURRENCE_NUMBER++))

      if [ -n "${OPT_OCCURRENCE_NUMBER}" ] && [ "${OPT_OCCURRENCE_NUMBER}" -eq \
          "${CURRENT_OCCURRENCE_NUMBER}" ]; then
        break 2
      fi
    fi
  done
done

if [ "${#MATCHES[@]}" -gt 0 ]; then
  if [ -n "${OPT_OCCURRENCE_NUMBER}" ]; then
    echo "${MATCHES[$((${#MATCHES[@]} - 1))]}"
  else
    echo "${MATCHES[0]}"
  fi
fi

