#!/usr/bin/env bash
# 
# Locate a file or directory from a database.
# 

readonly HERE="$(dirname "${0}")"
source "${HERE}/CONSTANTS.sh"

printHelpMessage() {
  echo -ne "\
locate

Usage:
  locate [options] <file or directory>

Options:
  -o <FIND_OCCURRENCE>
        find occurrence of file
  -d    locate a directory instead of a file
  -h    show help message
"
}

while getopts :o:dh OPT; do
  case "${OPT}" in
    o)
      if [[ ! "${OPTARG}" =~ ^[0-9]+$ ]]; then
        echo "locate: invalid value \"${OPTARG}\" for option -o" 1>&2
        exit 1
      else
        if [ -z "${OPTARG}" ]; then
          echo 'locate: missing argument for option -o' 1>&2
          exit 1
        fi
        OPT_FIND_OCCUR_NO="${OPTARG}"
      fi
      ;;
    d) OPT_FIND_DIRECTORIES=true;;
    h) printHelpMessage; exit;;
    \?)
      echo "locate: option \"${OPTARG}\" is unknown" 1>&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))


if [ $# -eq 0 ]; then
  echo 'locate: no file name specified' 1>&2
  exit 1
fi

# ========================================================
#   Set up mountpoint directories
# ========================================================

for mntpntDir in "${MNTPNT_PATHS[@]}"; do
  if [ -d "${mntpntDir}" ] && mountpoint "${mntpntDir}" >/dev/null; then
    mntpntDirsTmp+=("${mntpntDir}")
  fi
done

MNTPNT_PATHS=("${mntpntDirsTmp[@]}")

# ========================================================
#   Start the search
# ========================================================

if [ "${OPT_FIND_DIRECTORIES}" = 'true' ]; then
  CURR_DB_DIR="${DIR_PATHS_DB_DIR}"
else
  CURR_DB_DIR="${FILE_PATHS_DB_DIR}"
fi

for dbFileName in "${DB_FILE_NAMES[@]}"
do
  if [ ! -f "${CURR_DB_DIR}/${dbFileName}" ]; then
    continue
  fi

  for mtch in $(grep -P "(?<=/)([^/]*)(?=[^/]*${1}[^/]*$)" \
      "${CURR_DB_DIR}/${dbFileName}"); do

    if [[ "${mtch}" = '{MNTPNT_PATH}/'* ]]; then
      for mntpntDir in "${MNTPNT_PATHS[@]}"; do
        mntpntDirMtchPrsd="${mtch//'{MNTPNT_PATH}'/"${mntpntDir}"}"

        if [[ ("${OPT_FIND_DIRECTORIES}" = 'true' && -d \
            "${mntpntDirMtchPrsd}") || -f "${mntpntDirMtchPrsd}" ]]; then
          FOUND_MATCHES+=("${mntpntDirMtchPrsd}")
          ((CURR_OCCUR_NO++))
          
          [[ "${OPT_FIND_OCCUR_NO}" -eq "${CURR_OCCUR_NO}" ]] && break 3
        fi
      done
    else
      FOUND_MATCHES+=("${mtch}")
      ((CURR_OCCUR_NO++))

      [[ "${OPT_FIND_OCCUR_NO}" -eq "${CURR_OCCUR_NO}" ]] && break 2
    fi
  done
done

if [ "${#FOUND_MATCHES[@]}" -gt 0 ]; then
  if [ -n "${OPT_FIND_OCCUR_NO}" ]; then
    echo "${FOUND_MATCHES[$((${#FOUND_MATCHES[@]} - 1))]}"
  else
    echo "${FOUND_MATCHES[0]}"
  fi
fi

